---
version: '3'

tasks:
  default:
    desc: Build and test the project
    cmds:
      - task: build
      - task: test

  build:
    desc: Build the service and client binaries
    silent: true
    cmds:
      - go build -o bin/service ./cmd/service
      - go build -o bin/client ./cmd/client

  test:
    desc: Run tests with coverage
    silent: true
    cmds:
      - go test -race -coverprofile=coverage.out ./...

  lint:
    desc: Run golangci-lint
    silent: true
    cmds:
      - golangci-lint run
